# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ScrapReporter news

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 23 * * 0"

jobs:
  run-all-scrapers:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.2"]
    permissions:
      contents: write
      issues: write
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        [ -f diff_changed/requirements.txt ] && pip install -r diff_changed/requirements.txt
        [ -f diff_keyword/requirements.txt ] && pip install -r diff_keyword/requirements.txt
        [ -f requirements.txt ] && pip install -r requirements.txt

    - name: Run diff_changed Scraper
      working-directory: diff_changed
      run: python "scrap.py"

    - name: Run diff_keyword Scraper
      working-directory: diff_keyword
      run: python "scrap.py"

    - name: Run secu_news Scraper
      run: python "secu_news.py"

    - name: Create issue
      env:
        ACTION_ACCESS_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
      run: python "create_issue.py"

    - name: Commit and Push Changes
      run: |
        git config --local user.email "hwantagexsw2@gmail.com"
        git config --local user.name "hwantage"
        
        git add diff_changed/ diff_keyword/ .
        
        if ! git diff-index --quiet HEAD; then
          git commit -m "Auto - Update data and create issue"
          git push origin master
        else
          echo "No changes to commit."
        fi
